name: "CI (integração continua): Main workflow"

on: 

  push:
    branches: ["main"]

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run npm install
        run: npm install
      
      - name: Run intall playwright
        run:  npx playwright install

      - name: Run test playwright
        run:  npx playwright test
